title: Audit4Improve
description: > # this means to ignore newlines until "baseurl:"
  Documentaci√≥n de la API Audit4Improve, c√≥digo base para la asignatura Factor√≠as de Software, del MUIT de la US
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      theme: jekyll-theme-cayman
      author: Isabel Rom·n
      email: irm@us.es
